version: '3'
services:
  postgres:
    restart: always
    security_opt:
      - seccomp:unconfined
    image: vrestihnat/pgsql96-rpi-zero 
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=postgres
    expose:
      - '5432'    
    ports:
            - 5432:5432

